package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/zhukovaskychina/xmysql-server/server/innodb/metadata"
)

// These auxiliary INFORMATION_SCHEMA tables are catalog shells. XMySQL does
// still leaves plugin-owned and FULLTEXT-specific catalog data to their
// respective optional subsystems, but durable InnoDB tablespace/file metadata
// and ANALYZE-backed column statistics are projected by dedicated handlers.

func informationSchemaAuxiliarySelect(query, table string, columns []string) *SelectResult {
	return newInformationSchemaSelectResult("information_schema."+table, requestedInformationSchemaColumns(query, columns), nil)
}

func (e *XMySQLExecutor) executeInformationSchemaColumnStatisticsSelect(query string) *SelectResult {
	const table = "column_statistics"
	columns := requestedInformationSchemaColumns(query, []string{
		"SCHEMA_NAME", "TABLE_NAME", "COLUMN_NAME", "HISTOGRAM",
	})
	if e == nil || e.infosSchemaManager == nil {
		return newInformationSchemaSelectResult("information_schema."+table, columns, nil)
	}

	filters := informationSchemaMetadataFilters(query)
	rows := make([][]interface{}, 0)
	for _, tableMeta := range e.scanFrmTables() {
		if !metadataPatternMatches(tableMeta.schemaName, filters["schema_name"]) ||
			!metadataPatternMatches(tableMeta.tableName, filters["table_name"]) {
			continue
		}
		stats, err := e.infosSchemaManager.GetTableStats(context.Background(), tableMeta.schemaName, tableMeta.tableName)
		if err != nil || stats == nil || stats.RowCount == 0 || len(stats.ColumnStats) == 0 {
			continue
		}

		columnNames := make([]string, 0, len(tableMeta.columns))
		for _, column := range tableMeta.columns {
			columnNames = append(columnNames, column.name)
		}
		for _, columnName := range columnNames {
			if !metadataPatternMatches(columnName, filters["column_name"]) {
				continue
			}
			stat, ok := informationSchemaColumnStat(stats.ColumnStats, columnName)
			if !ok || stat.HistogramDropped || stat.MinValue == nil || stat.MaxValue == nil {
				continue
			}
			histogram, err := informationSchemaHistogramJSON(stats.RowCount, stat)
			if err != nil {
				continue
			}
			values := map[string]interface{}{
				"SCHEMA_NAME": tableMeta.schemaName,
				"TABLE_NAME":  tableMeta.tableName,
				"COLUMN_NAME": columnName,
				"HISTOGRAM":   histogram,
			}
			if performanceSchemaLockValuesMatch(query, values) {
				rows = append(rows, projectInformationSchemaRow(columns, values))
			}
		}
	}
	sort.SliceStable(rows, func(i, j int) bool {
		return fmt.Sprint(rows[i]) < fmt.Sprint(rows[j])
	})
	return newInformationSchemaSelectResult("information_schema."+table, columns, rows)
}

func informationSchemaColumnStat(stats map[string]metadata.Stats, columnName string) (metadata.Stats, bool) {
	for name, stat := range stats {
		if strings.EqualFold(name, columnName) {
			return stat, true
		}
	}
	return metadata.Stats{}, false
}

// informationSchemaHistogramJSON prefers the explicitly persisted histogram
// generated by ANALYZE TABLE ... UPDATE HISTOGRAM. Older statistics sidecars
// only contain scalar min/max/NDV/null facts, so they retain the deterministic
// one-bucket fallback for backward compatibility.
func informationSchemaHistogramJSON(rowCount uint64, stat metadata.Stats) (string, error) {
	if rowCount == 0 {
		return "", fmt.Errorf("histogram row count is zero")
	}
	nullFraction := float64(stat.NullCount) / float64(rowCount)
	if nullFraction < 0 {
		nullFraction = 0
	}
	if nullFraction > 1 {
		nullFraction = 1
	}
	buckets := make([][]interface{}, 0)
	histogramType := "equi-height"
	samplingRate := 1.0
	numberOfBucketsSpecified := 1
	if stat.Histogram != nil && len(stat.Histogram.Buckets) > 0 {
		histogramType = stat.Histogram.HistogramType
		if histogramType == "" {
			histogramType = "equi-height"
		}
		if stat.Histogram.SamplingRate > 0 {
			samplingRate = stat.Histogram.SamplingRate
		}
		if stat.Histogram.NumberOfBucketsSpecified > 0 {
			numberOfBucketsSpecified = stat.Histogram.NumberOfBucketsSpecified
		}
		for _, bucket := range stat.Histogram.Buckets {
			cumulativeFrequency := bucket.CumulativeFrequency
			if cumulativeFrequency < 0 {
				cumulativeFrequency = 0
			}
			if cumulativeFrequency > 1 {
				cumulativeFrequency = 1
			}
			buckets = append(buckets, []interface{}{
				bucket.LowerBound,
				bucket.UpperBound,
				cumulativeFrequency,
				bucket.DistinctCount,
			})
		}
	}
	if len(buckets) == 0 {
		distinct := stat.DistinctCount
		if distinct == 0 {
			distinct = 1
		}
		buckets = append(buckets, []interface{}{stat.MinValue, stat.MaxValue, 1.0, distinct})
	}
	payload := map[string]interface{}{
		"buckets":                     buckets,
		"null-values":                 nullFraction,
		"sampling-rate":               samplingRate,
		"histogram-type":              histogramType,
		"number-of-buckets-specified": numberOfBucketsSpecified,
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshal column histogram: %w", err)
	}
	return string(raw), nil
}

func executeInformationSchemaTablespacesSelect(query string) *SelectResult {
	return informationSchemaAuxiliarySelect(query, "tablespaces", []string{
		"TABLESPACE_NAME", "ENGINE", "TABLESPACE_TYPE", "LOGFILE_GROUP_NAME",
		"EXTENT_SIZE", "AUTOEXTEND_SIZE", "MAXIMUM_SIZE", "NODEGROUP_ID",
		"TABLESPACE_COMMENT", "FILE_BLOCK_SIZE", "STATUS", "ENCRYPTION",
		"ENGINE_ATTRIBUTE", "SE_PRIVATE_DATA",
	})
}

func executeInformationSchemaFilesSelect(query string) *SelectResult {
	return informationSchemaAuxiliarySelect(query, "files", []string{
		"FILE_ID", "FILE_NAME", "FILE_TYPE", "TABLESPACE_NAME", "TABLE_CATALOG",
		"TABLE_SCHEMA", "TABLE_NAME", "LOGFILE_GROUP_NAME", "LOGFILE_GROUP_NUMBER",
		"ENGINE", "FULLTEXT_KEYS", "DELETED_ROWS", "UPDATE_COUNT", "FREE_EXTENTS",
		"TOTAL_EXTENTS", "EXTENT_SIZE", "INITIAL_SIZE", "MAXIMUM_SIZE",
		"AUTOEXTEND_SIZE", "CREATION_TIME", "LAST_UPDATE_TIME", "LAST_ACCESS_TIME",
		"RECOVER_TIME", "TRANSACTION_COUNTER", "VERSION", "ROW_FORMAT", "TABLE_ROWS",
		"AVG_ROW_LENGTH", "DATA_LENGTH", "MAX_DATA_LENGTH", "INDEX_LENGTH", "DATA_FREE",
		"CREATE_TIME", "UPDATE_TIME", "CHECK_TIME", "CHECKSUM", "STATUS", "EXTRA",
		"NODEGROUP_ID", "TABLESPACE_TYPE", "TABLESPACE_NAME", "FILE_NAME",
	})
}

// executeInformationSchemaConnectionControlFailedLoginAttemptsSelect exposes
// the live consecutive authentication-failure counters captured at the
// protocol boundary. A successful login removes the account row.
func (e *XMySQLExecutor) executeInformationSchemaConnectionControlFailedLoginAttemptsSelect(query string) *SelectResult {
	const table = "connection_control_failed_login_attempts"
	columns := requestedInformationSchemaColumns(query, []string{"USERHOST", "FAILED_ATTEMPTS"})
	if e == nil || e.metricsRecorder == nil {
		return newInformationSchemaSelectResult("information_schema."+table, columns, nil)
	}
	rows := make([][]interface{}, 0)
	for _, attempt := range e.metricsRecorder.FailedLoginAttempts() {
		if !informationSchemaConnectionControlUserHostMatches(query, attempt.UserHost) ||
			!performanceSchemaSummaryFilterMatches(query, "failed_attempts", fmt.Sprint(attempt.FailedAttempts)) {
			continue
		}
		rows = append(rows, projectInformationSchemaRow(columns, map[string]interface{}{
			"USERHOST": attempt.UserHost, "FAILED_ATTEMPTS": attempt.FailedAttempts,
		}))
	}
	return newInformationSchemaSelectResult("information_schema."+table, columns, rows)
}

func informationSchemaConnectionControlUserHostMatches(query, value string) bool {
	pattern := regexp.MustCompile(`(?is)\buserhost\s*(=|like)\s*'((?:''|[^'])*)'`)
	match := pattern.FindStringSubmatch(query)
	if len(match) != 3 {
		return true
	}
	filter := strings.ReplaceAll(match[2], "''", "'")
	if strings.EqualFold(match[1], "=") {
		return strings.EqualFold(value, filter)
	}
	return performanceSchemaSQLLike(filter, value)
}
